// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh1JrASJQS2kGZ5byyo-k4ZFdmQdRWe5k',
    appId: '1:388501979489:web:51a3d59569507808410520',
    messagingSenderId: '388501979489',
    projectId: 'smartattend-df71a',
    authDomain: 'smartattend-df71a.firebaseapp.com',
    storageBucket: 'smartattend-df71a.firebasestorage.app',
    measurementId: 'G-916GTZNBK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDatAo44mZ7psCzaI44tD4Hu-KyhXXNFaU',
    appId: '1:388501979489:android:5b79233f687e8acb410520',
    messagingSenderId: '388501979489',
    projectId: 'smartattend-df71a',
    storageBucket: 'smartattend-df71a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrA3fmM0KuHbiDwSmN3lEMro83i8Gi0so',
    appId: '1:388501979489:ios:99d36c870a9b1ad0410520',
    messagingSenderId: '388501979489',
    projectId: 'smartattend-df71a',
    storageBucket: 'smartattend-df71a.firebasestorage.app',
    iosBundleId: 'com.example.smartattend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrA3fmM0KuHbiDwSmN3lEMro83i8Gi0so',
    appId: '1:388501979489:ios:99d36c870a9b1ad0410520',
    messagingSenderId: '388501979489',
    projectId: 'smartattend-df71a',
    storageBucket: 'smartattend-df71a.firebasestorage.app',
    iosBundleId: 'com.example.smartattend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh1JrASJQS2kGZ5byyo-k4ZFdmQdRWe5k',
    appId: '1:388501979489:web:530ce76523ad2e79410520',
    messagingSenderId: '388501979489',
    projectId: 'smartattend-df71a',
    authDomain: 'smartattend-df71a.firebaseapp.com',
    storageBucket: 'smartattend-df71a.firebasestorage.app',
    measurementId: 'G-FJEP9GVFK4',
  );
}
